/**
 * @description       : 
 * @author            : eabhijith@gmail.com
 * @group             : 
 * @last modified on  : 03-28-2023
**/
public with sharing class UtilityConstants {

    
    public static final string SHIPMENT_STATUS_ON_TIME = 'Shipped- On Time';
    public static final string SHIPMENT_STATUS_NUMBER_MISSING = 'Error - Must provide tracking number';
    public static final string CONTACT_ADMIN_MESSAGE = 'Oops! Something went wrong please contanct adminstrator';
}